package br.com.qualiti.banco;

// Generated 02/03/2013 15:39:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TbCliente generated by hbm2java
 */
@Entity
@Table(name = "tb_cliente", catalog = "qualitibanco")
public class TbCliente implements java.io.Serializable {

	private String cpf;
	private String nome;
	private TbEndereco tbEndereco;
	private Set<TbGerentesCliente> tbGerentesClientes = new HashSet<TbGerentesCliente>(0);
	private Set<TbConta> tbContas = new HashSet<TbConta>(0);

	public TbCliente() {
	}

	public TbCliente(String cpf) {
		this.cpf = cpf;
	}

	public TbCliente(String cpf, String nome, TbEndereco tbEndereco,
			Set tbGerentesClientes, Set tbContas) {
		this.cpf = cpf;
		this.nome = nome;
		this.tbEndereco = tbEndereco;
		this.tbGerentesClientes = tbGerentesClientes;
		this.tbContas = tbContas;
	}

	@Id
	@Column(name = "cpf", unique = true, nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nome", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tbCliente")
	public TbEndereco getTbEndereco() {
		return this.tbEndereco;
	}

	public void setTbEndereco(TbEndereco tbEndereco) {
		this.tbEndereco = tbEndereco;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbCliente")
	public Set<TbGerentesCliente> getTbGerentesClientes() {
		return this.tbGerentesClientes;
	}

	public void setTbGerentesClientes(Set<TbGerentesCliente> tbGerentesClientes) {
		this.tbGerentesClientes = tbGerentesClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, 
			mappedBy = "tbCliente")
	public Set<TbConta> getTbContas() {
		return this.tbContas;
	}

	public void setTbContas(Set<TbConta> tbContas) {
		this.tbContas = tbContas;
	}

}
