package br.com.qualiti.banco;

// Generated 02/03/2013 15:39:02 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbGerentesCliente generated by hbm2java
 */
@Entity
@Table(name = "tb_gerentes_cliente", catalog = "qualitibanco")
public class TbGerentesCliente implements java.io.Serializable {

	private TbGerentesClienteId id;
	private TbGerente tbGerente;
	private TbCliente tbCliente;

	public TbGerentesCliente() {
	}

	public TbGerentesCliente(TbGerentesClienteId id) {
		this.id = id;
	}

	public TbGerentesCliente(TbGerentesClienteId id, TbGerente tbGerente,
			TbCliente tbCliente) {
		this.id = id;
		this.tbGerente = tbGerente;
		this.tbCliente = tbCliente;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tbGerenteId", column = @Column(name = "tb_gerente_id")),
			@AttributeOverride(name = "tbClienteCpf", column = @Column(name = "tb_cliente_cpf", length = 11)) })
	public TbGerentesClienteId getId() {
		return this.id;
	}

	public void setId(TbGerentesClienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_gerente_id", insertable = false, updatable = false)
	public TbGerente getTbGerente() {
		return this.tbGerente;
	}

	public void setTbGerente(TbGerente tbGerente) {
		this.tbGerente = tbGerente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_cliente_cpf", insertable = false, updatable = false)
	public TbCliente getTbCliente() {
		return this.tbCliente;
	}

	public void setTbCliente(TbCliente tbCliente) {
		this.tbCliente = tbCliente;
	}

}
