package br.com.qualiti.banco;

// Generated 02/03/2013 15:39:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbGerente generated by hbm2java
 */
@Entity
@Table(name = "tb_gerente", catalog = "qualitibanco")
public class TbGerente implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String fone;
	private String celular;
	private String email;
	private Set<TbGerentesCliente> tbGerentesClientes = new HashSet<TbGerentesCliente>(0);

	public TbGerente() {
	}

	public TbGerente(String nome, String fone, String celular, String email,
			Set tbGerentesClientes) {
		this.nome = nome;
		this.fone = fone;
		this.celular = celular;
		this.email = email;
		this.tbGerentesClientes = tbGerentesClientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "fone", length = 12)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}

	@Column(name = "celular", length = 12)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbGerente")
	public Set<TbGerentesCliente> getTbGerentesClientes() {
		return this.tbGerentesClientes;
	}

	public void setTbGerentesClientes(Set<TbGerentesCliente> tbGerentesClientes) {
		this.tbGerentesClientes = tbGerentesClientes;
	}

}
