package br.com.qualiti.banco;

// Generated 02/03/2013 15:39:02 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbGerentesClienteId generated by hbm2java
 */
@Embeddable
public class TbGerentesClienteId implements java.io.Serializable {

	private Integer tbGerenteId;
	private String tbClienteCpf;

	public TbGerentesClienteId() {
	}

	public TbGerentesClienteId(Integer tbGerenteId, String tbClienteCpf) {
		this.tbGerenteId = tbGerenteId;
		this.tbClienteCpf = tbClienteCpf;
	}

	@Column(name = "tb_gerente_id")
	public Integer getTbGerenteId() {
		return this.tbGerenteId;
	}

	public void setTbGerenteId(Integer tbGerenteId) {
		this.tbGerenteId = tbGerenteId;
	}

	@Column(name = "tb_cliente_cpf", length = 11)
	public String getTbClienteCpf() {
		return this.tbClienteCpf;
	}

	public void setTbClienteCpf(String tbClienteCpf) {
		this.tbClienteCpf = tbClienteCpf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbGerentesClienteId))
			return false;
		TbGerentesClienteId castOther = (TbGerentesClienteId) other;

		return ((this.getTbGerenteId() == castOther.getTbGerenteId()) || (this
				.getTbGerenteId() != null && castOther.getTbGerenteId() != null && this
				.getTbGerenteId().equals(castOther.getTbGerenteId())))
				&& ((this.getTbClienteCpf() == castOther.getTbClienteCpf()) || (this
						.getTbClienteCpf() != null
						&& castOther.getTbClienteCpf() != null && this
						.getTbClienteCpf().equals(castOther.getTbClienteCpf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTbGerenteId() == null ? 0 : this.getTbGerenteId()
						.hashCode());
		result = 37
				* result
				+ (getTbClienteCpf() == null ? 0 : this.getTbClienteCpf()
						.hashCode());
		return result;
	}

}
