package br.com.qualiti.banco.hibernate;

// Generated 02/03/2013 14:55:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "tb_cliente", catalog = "qualitiBanco")
public class Cliente implements java.io.Serializable {

	private String cpf;
	private String nome;

	public Cliente() {
	}

	public Cliente(String cpf) {
		this.cpf = cpf;
	}

	public Cliente(String cpf, String nome) {
		this.cpf = cpf;
		this.nome = nome;
	}

	@Id
	@Column(name = "cpf", unique = true, nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "nome", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
