package br.com.qualiti.banco.hibernate;

// Generated 02/03/2013 14:55:08 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbEndereco generated by hbm2java
 */
@Entity
@Table(name = "tb_endereco", catalog = "qualitiBanco")
public class TbEndereco implements java.io.Serializable {

	private String tbClienteCpf;
	private String cep;
	private String numero;
	private String complemento;

	public TbEndereco() {
	}

	public TbEndereco(String tbClienteCpf) {
		this.tbClienteCpf = tbClienteCpf;
	}

	public TbEndereco(String tbClienteCpf, String cep, String numero,
			String complemento) {
		this.tbClienteCpf = tbClienteCpf;
		this.cep = cep;
		this.numero = numero;
		this.complemento = complemento;
	}

	@Id
	@Column(name = "tb_cliente_cpf", unique = true, nullable = false, length = 11)
	public String getTbClienteCpf() {
		return this.tbClienteCpf;
	}

	public void setTbClienteCpf(String tbClienteCpf) {
		this.tbClienteCpf = tbClienteCpf;
	}

	@Column(name = "cep", length = 8)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "numero", length = 5)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 100)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

}
