package br.com.qualiti.banco.hibernate;

// Generated 02/03/2013 14:55:08 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbGerentesCliente generated by hbm2java
 */
@Entity
@Table(name = "tb_gerentes_cliente", catalog = "qualitiBanco")
public class TbGerentesCliente implements java.io.Serializable {

	private TbGerentesClienteId id;

	public TbGerentesCliente() {
	}

	public TbGerentesCliente(TbGerentesClienteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tbGerenteId", column = @Column(name = "tb_gerente_id")),
			@AttributeOverride(name = "tbClienteCpf", column = @Column(name = "tb_cliente_cpf", length = 11)) })
	public TbGerentesClienteId getId() {
		return this.id;
	}

	public void setId(TbGerentesClienteId id) {
		this.id = id;
	}

}
